FROM flink:2.0.0-scala_2.12-java17

RUN echo "--> Setup Directory Structure" && \
    mkdir -p /opt/flink/checkpoints && \
    mkdir -p /opt/flink/rocksdb && \
    mkdir -p /opt/flink/log

RUN echo "--> Install JARs: Flink's S3 plugin" && \
    mkdir ./plugins/s3-fs-hadoop && \
    mv ./opt/flink-s3-fs-hadoop-2.0.0.jar ./plugins/s3-fs-hadoop/

RUN echo "--> Install Flink JARs: Generic"
COPY stage/bundle-2.31.9.jar                            /opt/flink/lib/bundle-2.31.9.jar  
COPY stage/flink-shaded-hadoop-2-uber-2.8.3-10.0.jar    /opt/flink/lib/flink-shaded-hadoop-2-uber-2.8.3-10.0.jar
COPY stage/paimon-s3-1.2.0.jar                          /opt/flink/lib/paimon-s3-1.2.0.jar

COPY stage/postgresql-42.7.6.jar                          /opt/flink/lib/postgresql-42.7.6.jar
# CDC Support https://nightlies.apache.org/flink/flink-cdc-docs-release-3.4/docs/connectors/flink-sources/overview/#supported-flink-versions
COPY stage/flink-sql-connector-postgres-cdc-3.5.0.jar   /opt/flink/lib/flink-sql-connector-postgres-cdc-3.5.0.jar
COPY stage/flink-sql-connector-kafka-4.0.0-2.0.jar      /opt/flink/lib/flink-sql-connector-kafka-4.0.0-2.0.jar
COPY stage/paimon-flink-2.0-1.2.0.jar                     /opt/flink/lib/paimon-flink-2.0-1.2.0.jar

COPY stage/flink-sql-json-2.0.0.jar                      /opt/flink/lib/flink-sql-json-2.0.0.jar     
COPY stage/flink-sql-parquet-2.0.0.jar                   /opt/flink/lib/flink-sql-parquet-2.0.02.jar
COPY stage/flink-json-2.0.0.jar                          /opt/flink/lib/stage/flink-json-2.0.0.jar


RUN chown -R flink:flink /opt/flink
